[package]
name = "LumioTokenObjects"
version = "1.0.0"

[addresses]
std = "0x1"
lumio_std = "0x1"
lumio_framework = "0x1"
lumio_token_objects = "0x4"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
LumioFramework = { local = "../lumio-framework"}
