[package]
name = "LumioToken"
version = "1.0.0"

[addresses]
std = "0x1"
lumio_framework = "0x1"
lumio_token = "0x3"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
LumioFramework = { local = "../lumio-framework"}
