[package]
name = "LumioFramework"
version = "1.0.0"

[addresses]
std = "0x1"
lumio_std = "0x1"
lumio_framework = "0x1"
lumio_fungible_asset = "0xA"
lumio_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"

[dependencies]
LumioStdlib = { local = "../lumio-stdlib" }
MoveStdlib = { local = "../move-stdlib" }
